
-- Decompiled with the Synapse X Luau decompiler.

return {
	typeList = {
		kill = { "Enemy Killed!" }, 
		collx2 = { "Double Collateral!" }, 
		collx3 = { "Triple Collateral!" }, 
		collxn = { "Multi Collateral!" }, 
		killx2 = { "Double Kill!" }, 
		killx3 = { "Triple Kill!" }, 
		killx4 = { "Quad Kill!" }, 
		killxn = { "Multi Kill!" }, 
		backstab = { "Backstab!" }, 
		assist = { "Assist!" }, 
		suppression = { "Suppressed Enemy!" }, 
		assistkill = { "Assist Count As Kill!" }, 
		head = { "Headshot Bonus!" }, 
		wall = { "Wallbang Bonus!" }, 
		spot = { "Spot Bonus!" }, 
		long = { "Killed from a distance!", "Long Shot!" }, 
		squad = { "Teammate spawned on you", "Squadmate spawned on you" }, 
		flagsteal = { "Acquired Enemy Flag!", "Stolen Enemy Flag!" }, 
		flagcapture = { "Captured Enemy Flag!" }, 
		flagteamcap = { "Team Captured Enemy Flag!" }, 
		flagrecover = { "Recovered Team Flag!" }, 
		flagdef1 = { "Killed Enemy Flag Carrier!" }, 
		flagdef2 = { "Protected Flag Carrier!" }, 
		flagdef3 = { "Denied Enemy Capture!" }, 
		flagdef4 = { "Denied Enemy Pick Up!" }, 
		flagdef5 = { "Flag Guard Kill!" }, 
		flagdef6 = { "Flag Recover Kill!" }, 
		flagsup1 = { "Flag Escort Kill!" }, 
		flagsup2 = { "Killed Enemy Flag Escort!" }, 
		flagsup3 = { "Assisted by Teammate!" }, 
		flagsup4 = { "Protected Flag Carrier Under Fire!", "Protected Flag Carrier!" }, 
		flagsup5 = { "Saved by Teammate!" }, 
		flagsup6 = { "Protected by Teammate!" }, 
		flagoff1 = { "Offensive Flag Kill!" }, 
		flagoff2 = { "Denied Enemy Flag Recovery!" }, 
		flagoff3 = { "Killed Enemy Flag Guard!" }, 
		dogtagself = { "Secured Personal Tag!" }, 
		dogtagconfirm = { "Kill Confirmed!" }, 
		dogtagteam = { "Teammate Confirmed Kill!" }, 
		dogtagdeny = { "Denied Enemy Kill!" }, 
		domcap = { "Captured a position!" }, 
		domcapping = { "Capturing position" }, 
		domdefend = { "Defended a position!" }, 
		domassault = { "Assaulted a position!" }, 
		domattack = { "Attacked a position!" }, 
		dombuzz = { "Stopped an enemy capture!" }, 
		kingcap = { "Captured the hill!" }, 
		kingholding = { "Holding hill" }, 
		kingcapping = { "Capturing hill" }, 
		hphold = { "Holding point!", "Holding position!" }, 
		hpdefend = { "Defended position!", "Defended point!" }, 
		hpassault = { "Assaulted point!", "Assaulted position!" }, 
		hpattack = { "Attacked position!", "Attacked point!" }, 
		tagsecure = { "Secured Enemy Tag!" }, 
		tagteam = { "Secured Friendly Tag!" }, 
		tagredeem = { "Redeemed Enemy Tags!" }, 
		tagrecover = { "Recovered Friendly Tags!" }
	}
};

